// Fallback survey data when database is unavailable
const now = new Date();

export const fallbackSurveys = [
  {
    id: 'survey_1',
    title: '대학 캠퍼스 시설 만족도 조사',
    description: '우리 캠퍼스의 다양한 시설에 대한 의견을 수집하고 있습니다.',
    creatorId: 'user_1',
    creator: {
      id: 'user_1',
      nickname: '학생회',
      department: '학생회',
      grade: 3,
    },
    status: 'ACTIVE',
    category: 'CAMPUS',
    targetDepartments: [],
    targetGrades: [],
    maxResponses: 100,
    currentResponses: 1,
    rewardType: 'POINT',
    rewardAmount: 500,
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 5,
    questions: [
      {
        id: 'q1',
        orderIndex: 1,
        type: 'SINGLE_CHOICE',
        title: '도서관 만족도',
        isRequired: true,
        options: JSON.stringify(['매우 만족', '만족', '보통', '불만족', '매우 불만족']),
      },
      {
        id: 'q2',
        orderIndex: 2,
        type: 'SINGLE_CHOICE',
        title: '식당 만족도',
        isRequired: true,
        options: JSON.stringify(['매우 만족', '만족', '보통', '불만족', '매우 불만족']),
      },
    ],
  },
  {
    id: 'survey_2',
    title: '온라인 강의 플랫폼 개선 의견 수집',
    description: '현재 사용 중인 온라인 강의 플랫폼에 대한 피드백을 받습니다.',
    creatorId: 'user_2',
    creator: {
      id: 'user_2',
      nickname: '교수님',
      department: '컴퓨터공학과',
      grade: 0,
    },
    status: 'ACTIVE',
    category: 'ACADEMIC',
    targetDepartments: [],
    targetGrades: [],
    maxResponses: 150,
    currentResponses: 0,
    rewardType: 'POINT',
    rewardAmount: 300,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 8,
    questions: [
      {
        id: 'q3',
        orderIndex: 1,
        type: 'SINGLE_CHOICE',
        title: '온라인 강의 플랫폼을 자주 이용하시나요?',
        isRequired: true,
        options: JSON.stringify(['자주 이용', '가끔 이용', '거의 이용하지 않음']),
      },
    ],
  },
  {
    id: 'survey_3',
    title: '대학생 일상생활 비용 조사',
    description: '한국 대학생들의 월평균 생활비 및 소비 패턴에 관한 조사입니다.',
    creatorId: 'user_3',
    creator: {
      id: 'user_3',
      nickname: '연구원',
      department: '경영학과',
      grade: 2,
    },
    status: 'ACTIVE',
    category: 'RESEARCH',
    targetDepartments: [],
    targetGrades: [],
    maxResponses: 50,
    currentResponses: 0,
    rewardType: 'POINT',
    rewardAmount: 1000,
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 10,
    questions: [
      {
        id: 'q4',
        orderIndex: 1,
        type: 'SINGLE_CHOICE',
        title: '월평균 생활비는?',
        isRequired: true,
        options: JSON.stringify(['100만원 미만', '100-200만원', '200-300만원', '300만원 이상']),
      },
    ],
  },
];
